# Generated by Django 4.0.2 on 2022-02-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_appointments_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='state',
            field=models.CharField(choices=[('canceld by doctor', 'canceld by doctor'), ('canceld', 'canceld'), ('in processing', 'in processing'), ('missed', 'missed'), ('finished', 'finished'), ('reschedule', 'reschedule'), ('approved', 'approved')], max_length=20, null=True),
        ),
    ]
